### ISSUE TITLE
Charts not exported to PDF when the slide has a title [Marmota 22.35.1]

### ISSUE THREAD

**Issue by McPringle** [marmota-app/feedback#11]
When the slide has a title, the chart will be displayed in the preview and the presentation but missing in the PDF export/printout. Example files (source and PDF) are attached.

[Example.md](https://github.com/marmota-app/feedback/files/9683072/Example.md)
[Example.pdf](https://github.com/marmota-app/feedback/files/9683073/Example.pdf)

**Comment by dtanzer** [comment]
Fixed in next release.

**Comment by dtanzer** [comment]
22.40.0
