### ISSUE TITLE
Some images do not show up in the PDF export [Marmota 22.35.1]

### ISSUE THREAD

**Issue by McPringle** [marmota-app/feedback#12]
When I export a presentation with images, some of them do not show up in the exported PDF file. See attached example:

[Example.zip](https://github.com/marmota-app/feedback/files/9683135/Example.zip)

The images are shown as intended in the preview and presentation. Maybe it has to do with the dimensions of the images.

This issue might be related to #11: The chart is bigger than the slide. If elements stick out of the area, they will not be included in the PDF.

**Comment by dtanzer** [comment]
Fixed in next release

**Comment by dtanzer** [comment]
22.40.0
