### ISSUE TITLE
Numbers in charts shown as floating point number [Marmota 22.35.1]

### ISSUE THREAD

**Issue by McPringle** [marmota-app/feedback#9]
The following Markdown:
```markdown
{design=marmota.app/dark}

#{shadow=true} Chart Test
| Version | JEPs |{chart;type=bar}
| ------- | ---- |
|       A |   50 |
|       B |   91 |

```

produces the following output:
![image](https://user-images.githubusercontent.com/1254039/193242478-27f493ca-a5ff-4f16-a69f-1c5cd92448ea.png)

When I provide values without decimal places in the table, I also expect values without decimal places in the chart. Not a big deal, but looks "strange".

**Comment by dtanzer** [comment]
I don't want marmota to try to find out the "correct" precision automatically, since it's hard to decide what "correct" is. I will add a configuration option to set the precision.

**Comment by dtanzer** [comment]
Fixed in next release.

**Comment by dtanzer** [comment]
22.40.0

**Comment by dtanzer** [comment]
https://marmota.app/docs/editing/charts/#y-axis-options
